In [1]:
import pandas as pd
import datetime

In [2]:
transactions = pd.read_excel('C:\\Users\\reiav\\OneDrive\\Desktop\\Budget_excel.xlsx')
transactions['Date_Timestamp'] = transactions['Date'].apply(lambda x: pd.Timestamp(x))
new_transactions = pd.read_csv('C:\\Users\\reiav\\Downloads\\transactions.csv')
new_transactions['Date_Timestamp'] = new_transactions['Date'].apply(lambda x: pd.Timestamp(x))
new_transactions_reduced = []

In [3]:
transactions.dtypes

Month                            int64
Year                             int64
Date                    datetime64[ns]
Description                     object
Original Description            object
Amount                         float64
Transaction Type                object
Category                        object
Account Name                    object
Actual Amount                  float64
Labels                         float64
Notes                          float64
Date_Timestamp          datetime64[ns]
dtype: object

In [4]:
new_transactions.dtypes

Date                            object
Description                     object
Original Description            object
Amount                         float64
Transaction Type                object
Category                        object
Account Name                    object
Labels                         float64
Notes                           object
Date_Timestamp          datetime64[ns]
dtype: object

In [5]:
year = 2019
month = 6

def dateFilter(df, year, month):
    return df['Date_Timestamp'].apply(lambda x: (x.year >= year) and (x.month >= month))

for index, new_transaction in new_transactions[dateFilter(new_transactions, year, month)].iterrows():
    contains = False
    for index2, transaction in transactions[dateFilter(transactions, year, month)].iterrows():
        isEqual = (pd.Timestamp(new_transaction['Date']) == pd.Timestamp(transaction['Date'])) and \
            (new_transaction['Description'] == transaction['Description']) and \
            (new_transaction['Original Description'] == transaction['Original Description']) and \
            ((transaction['Amount'] - 0.01) < new_transaction['Amount'] < (transaction['Amount'] + 0.01)) and \
            (new_transaction['Transaction Type'] == transaction['Transaction Type']) and \
            (new_transaction['Account Name'] == transaction['Account Name'])
        if isEqual:
            contains = True
    if not contains:
        new_transactions_reduced.append(new_transaction)
new_transactions_reduced = pd.DataFrame(new_transactions_reduced)
new_transactions_reduced = new_transactions_reduced[new_transactions_reduced['Original Description'].apply(lambda x: not str(x).strip().startswith('Auth : '))]
new_transactions_reduced

,Date,Description,Original Description,Amount,Transaction Type,Category,Account Name,Labels,Notes,Date_Timestamp
5,6/14/2019,06/13 card 1746 Smiths Fu 5564 Cnorth Las Venv,Debit Purchase 06/13 card 1746 Smiths Fu 5564 ...,51.19,debit,Gas & Fuel,Main Checking,NaN,NaN,2019-06-14
6,6/14/2019,payment Connie Burton,Web Authorized Pmt Connie Burton,79.80,debit,Financial,Main Checking,NaN,NaN,2019-06-14
7,6/14/2019,Paparazzi Llc 855-697-2727 Ut,Paparazzi Llc 855-697-2727 Ut,100.83,debit,Misc Expenses,Cassie's Reward Card,NaN,NaN,2019-06-14
8,6/14/2019,Wal-Mart,Wm Supercenter #4339 North Las Veg Nv,12.09,debit,Shopping,Cassie's Reward Card,NaN,NaN,2019-06-14
9,6/14/2019,Ww Int'l-franchise 800-651-6000 Ny,Ww Int'l-franchise 800-651-6000 Ny,51.00,debit,Charity,Cassie's Reward Card,NaN,NaN,2019-06-14
10,6/14/2019,Redbox,Redbox Dvd Rental Oakbrook Ter Il,1.89,debit,Movies & DVDs,Ryan's Reward Card,NaN,NaN,2019-06-14
11,6/13/2019,Smith's Food,Smiths Food #4334 0000 North Las Veg Nv,112.78,debit,Groceries,Ryan's Reward Card,NaN,NaN,2019-06-13
12,6/13/2019,Cox Communications,Cox Communicat055430 5 Las Vegas Nv,6.51,debit,Television,Ryan's Reward Card,NaN,NaN,2019-06-13
13,6/13/2019,Nv Energy South,Electronic Withdrawal Nv Energy South,15.10,debit,Utilities,Main Checking,NaN,NaN,2019-06-13
14,6/13/2019,Phone Authorized payment Gateway One Lend,Phone Authorized Pmt Gateway One Lend,1500.00,debit,Auto Payment,Main Checking,NaN,NaN,2019-06-13
15,6/13/2019,Monthly Maintenance Fee,Monthly Maintenance Fee,14.95,debit,Bank Fee,Main Checking,NaN,NaN,2019-06-13
16,6/13/2019,-visa 06/11 card 2863 Ann Road Animal North La...,Debit Purchase -visa 06/11 card 2863 Ann Road ...,25.98,debit,Veterinary,Main Checking,NaN,NaN,2019-06-13
17,6/13/2019,Monthly Maintenance Fee Waived,Monthly Maintenance Fee Waived,14.95,credit,Bank Fee,Main Checking,NaN,NaN,2019-06-13
18,6/13/2019,SUNRISE FOOD MART,SUNRISE FOOD MART,25.12,debit,Food & Dining,CREDIT CARD,NaN,NaN,2019-06-13
19,6/13/2019,Sweet Tomatoes,SWEET TOMATOES 119,15.46,debit,Groceries,CREDIT CARD,NaN,NaN,2019-06-13
20,6/12/2019,IKEA,Ikea Las Vegas Las Vegas Nv,63.26,debit,Furnishings,Cassie's Reward Card,NaN,NaN,2019-06-12
21,6/12/2019,Paparazzi Llc 855-697-2727 Ut,Paparazzi Llc 855-697-2727 Ut,80.35,debit,Misc Expenses,Cassie's Reward Card,NaN,NaN,2019-06-12
40,6/07/2019,Cox Enterprises,Electronic Deposit Cox Enterprises,3069.78,credit,Income,Main Checking,NaN,NaN,2019-06-07

In [6]:
new_transactions_reduced.to_csv('C:\\Users\\reiav\\Downloads\\transactions_new.csv')